name: "[gazelle] check"

on:
  push:
    branches:
      - master
      - main
  pull_request: 
  merge_group:

permissions:
  contents: read
  
jobs:
  gazelle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          show-progress: false
          fetch-depth: 1

      - uses: bazel-contrib/setup-bazel@0.13.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true
          
      - name: Setup Bazel
        run: |
          cat <<EOF > ~/.bazelrc
          build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}
          build --build_metadata=ROLE=CI
          EOF
          
      - name: Check
        run: bazel run //:gazelle -- --mode=diff