name: golangci-lint
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read
  pull-requests: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v4
        with:
          show-progress: false
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true
          fetch-depth: 0
      
      - uses: bazel-contrib/setup-bazel@0.13.0
        with:
          # Avoid downloading Bazel every time.
          bazelisk-cache: true
          # Store build cache per workflow.
          disk-cache: ${{ github.workflow }}
          # Share repository cache between workflows.
          repository-cache: true

      - name: Setup Bazel
        run: |
          cat <<EOF > ~/.bazelrc
          build --remote_header=x-buildbuddy-api-key=${{ secrets.BUILDBUDDY_API_KEY }}
          build --build_metadata=ROLE=CI
          EOF

      - name: Lint
        run: make lint
